name: PetBoarding
run-name: PetBoardingCI
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch: # Enables manual trigger

env:
  SOLUTION_FILE_PATH: PetBoarding.sln
  BUILD_CONFIGURATION: Release
  PUBLISH_DIR: '${{ github.workspace }}/publish'
  PACKAGENAME: 'test-deploy'
  PACKAGE_TMP_DIR: '${{ github.workspace }}\\PetBoarding\\obj\\Release\\Package\\PackageTmp'

permissions:
  contents: read

jobs:
  build:
    name: BuildAndTest
    runs-on: windows

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      
    - name: Restore NuGet
      run: nuget restore PetBoarding.sln
      
    - name: Create Publish Directory
      run: mkdir -p ${{ env.PUBLISH_DIR }}

    - name: Build and Publish Web App
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: |
        msbuild ${{ env.SOLUTION_FILE_PATH }} /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageLocation=".\YourWebApp.zip" /t:Rebuild