// <auto-generated />
namespace WebAppTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class RemoveUnnecessaryMaxLengthfromRegisterViewModelName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveUnnecessaryMaxLengthfromRegisterViewModelName));
        
        string IMigrationMetadata.Id
        {
            get { return "202606082216199_Remove-Unnecessary-MaxLength-from-RegisterViewModel-Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
