// <auto-generated />
namespace WebAppTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Makeactualdatesnullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Makeactualdatesnullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202605061849552_Make 'actual' dates nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
